export const StringValues = {
  ReadMore: "Read More",
  TrendingBooks: "Trending Books",
  Popular: "Popular",
  Categories: "Categories",
  FreeBooks: "Free Books",
  BestSellers: "Best Sellers",
  NewWriters: "New Writers",
  PleaseCheckInternet: "Please check your internet connection and try again.",
  NoData: "No data available",
  Hi: "Hi",
  NotForSale: "Not For Sale",
  LatestBooks: "Latest Books",
  SearchForBooks: "Search For Books",
  UnKnownAuthor: "Unknown Author",
  SomethingWentWrong: "Something went wrong",
  SelectOption: " Select an Option",
  GoodMorning: "Good Morning",
  GooAfternoon: "Good AfterNoon",
  GoodEvening: "Good Evening",
  Author: "Author",
  Subtitle: "Subtitle",
  Publisher: "Publisher",
  PublishedDate: "Published date",
  Description: "Description",
  Overview: "Overview",
  BookId: "Book Id",
  Language: "Language",
  Price: "Price",
  NumberOfPages: "Number Of pages",
  Category: "Category",
  ComingSoon: "Coming soon",
};
